// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHa7tPaQ07O-OiZCkDA2VaG5xWieKFhDA',
    appId: '1:902457817168:web:b0646f68d35c4643ab3955',
    messagingSenderId: '902457817168',
    projectId: 'add-todolist-44ac2',
    authDomain: 'add-todolist-44ac2.firebaseapp.com',
    storageBucket: 'add-todolist-44ac2.firebasestorage.app',
    measurementId: 'G-BX2TZF28J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8pYwWOkbGyDr16_qNyKb0JuhKQASQtYE',
    appId: '1:902457817168:android:25c7a6d445ec76a2ab3955',
    messagingSenderId: '902457817168',
    projectId: 'add-todolist-44ac2',
    storageBucket: 'add-todolist-44ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Bn8jfj4TPgLUWT3HzBo5z5dyU5-bK4Y',
    appId: '1:902457817168:ios:daa72dab48f9079aab3955',
    messagingSenderId: '902457817168',
    projectId: 'add-todolist-44ac2',
    storageBucket: 'add-todolist-44ac2.firebasestorage.app',
    iosClientId:
        '902457817168-jruk95pfhmis0qq43ntkilndplddce1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Bn8jfj4TPgLUWT3HzBo5z5dyU5-bK4Y',
    appId: '1:902457817168:ios:daa72dab48f9079aab3955',
    messagingSenderId: '902457817168',
    projectId: 'add-todolist-44ac2',
    storageBucket: 'add-todolist-44ac2.firebasestorage.app',
    iosClientId:
        '902457817168-jruk95pfhmis0qq43ntkilndplddce1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHa7tPaQ07O-OiZCkDA2VaG5xWieKFhDA',
    appId: '1:902457817168:web:7c78bd1862c9318dab3955',
    messagingSenderId: '902457817168',
    projectId: 'add-todolist-44ac2',
    authDomain: 'add-todolist-44ac2.firebaseapp.com',
    storageBucket: 'add-todolist-44ac2.firebasestorage.app',
    measurementId: 'G-781KRHH8KD',
  );
}
